# Generated by Django 4.2.2 on 2023-06-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('registration_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
                ('values', models.CharField(max_length=200)),
                ('inspection_person', models.CharField(max_length=200)),
                ('car_brand', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('variant', models.CharField(max_length=200)),
                ('meter_reading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=100)),
                ('inspection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepartsapp.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepartsapp.inspection')),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparepartsapp.questions')),
            ],
        ),
    ]
